### PR TITLE
feat(ssh_tunnel): add support for authentication via ipv4 and ipv6

### PR DESCRIPTION
**Pull request by empwilli**
Some users of the situation faced the situation where redirect link the oauth2 flow was not invoked correctly. The problem here was that localhost was resolved differently, depending on the respective user's machine (either as IPv4 only or as IPv6 only). If the redirect server, however, bound to the opposing protocol, the resolver link did not work.

To the best of our knowledge, this is an issue with actix (or underlying crates), as the "bind" method promises to bind to either IPv4 and IPv6 if "localhost" is specified.

With this fix we resolve the issue by extending the authentication info so that multiple bind addresses can be specified. We then explicitly specify both, the IPv4 and the IPv6 localhost addresses.

### CODE REVIEW

**Comment by empwilli** [comment]
Note: this requires an update of the test config in our test plan

**Comment by JanZachmann** [comment]
> Note: this requires an update of the test config in our test plan

can you explain why?

**Comment by empwilli** [comment]
> > Note: this requires an update of the test config in our test plan
> 
> do you mean the concourse pipeline test? can you explain why?

In our test plans we provide a test configuration for the ssh connection environment. With this change we now provide a list of bind addresses instead of a single one, the test plan configuration must be updated accordingly. The note above was a reminder to update that config as soon as the PR is merged.

**Review by JanZachmann — APPROVED** [review]
@empwilli 
Imho we should change PR title. The value in brackets is supposed to be a feature.

- fix(ssh_tunnel): add support for authentication via ipv4 and ipv6
- feat(ssh_tunnel): add support for authentication via ipv4 and ipv6

**Review by JoergZeidler — APPROVED** [review]

**Pull request merged**
